export const FETCH_START_TICKER = 'FETCH_START_TICKER';
export const FETCH_FINISH_TICKER = 'FETCH_FINISH_TICKER';
export const ERROR = 'ERROR';

export const FETCH_START_TRADES = 'FETCH_START_TRADES';
export const FETCH_FINISH_TRADES = 'FETCH_FINISH_TRADES';